### ISSUE TITLE
Use non-exportable in memory certificate from certificate store

### ISSUE THREAD

**Issue by tsaridas** [hakril/PythonForWindows#1]
Hi there,

Is there any option to use a client certificate for x509 purposes using these libraries ?

**Comment by hakril** [comment]
Hi,

Can you give me more information about what you are trying to do, please? So I can tell you if the feature exists or could be implemented.

If you are trying to work with CertificateStore you can use the class [windows.crypto.EHCERTSTORE](http://hakril.github.io/PythonForWindows/build/html/crypto.html#windows.crypto.EHCERTSTORE) that allows you to create new certificate store in memory or open existing certificate store from a file or a system store.

Exemple:

```
>>> windows.crypto.EHCERTSTORE
<class 'windows.crypto.certificate.EHCERTSTORE'>
>>> windows.crypto.EHCERTSTORE.from_file("MyCertStore.sst")
<EHCERTSTORE object at 0x0452F710>
>>> cert_store = windows.crypto.EHCERTSTORE.from_file("MyCertStore.sst")
>>> cert_store
<EHCERTSTORE object at 0x0452F210>
>>> cert_store.certs[0]
<CertificateContext "Microsoft Root Certificate Authority" serial="79 ad 16 a1 4a a0 a5 ad 4c 73 58 f4 07 13 2e 65">
```

**Comment by tsaridas** [comment]
I'm trying to load a which a certificate is non exportable from the store and use it for client x.509 authentication (https request).
I figured how to do this thanks.
