### ISSUE TITLE
[DOC] FunctionCallBP not documented

### ISSUE THREAD

**Issue by BrunoPujos** [hakril/PythonForWindows#13]
The class `windows.debug.FunctionCallBP` (`breakpoints.py`) does not seems to be documented. This is the parent class  of `windows.debug.FunctionBP`. This class is useful when putting "by hand" a breakpoint on the start of a function and want to manipulate its return value when we do not have symbols or don't know the argument of the function. Simple example and documentation could be a potential improvement for this.

**Comment by hakril** [comment]
Hi,
Thank you for the issue. Indeed `FunctionCallBP ` can proove userful in some case.
I have added a sample based on this feature and also added `windows.debug.FunctionCallBP` to the `debug.rst` doc file.
The documentation will be updated om the online documentation the next time I merge master.

I am closing this issue, feel free to re-open it if you feel the sample is not descritive enought of the features you had in mind.
