### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by lucasg** [hakril/PythonForWindows#15]
Hi, 

There still some `basestring` uses in the codebase without the corresponding `pycompat` import, making it raise an Exception when used on python3.

Files impacted : 

* windows/winobject/event_trace.py
* windows/debug/breakpoints.py
* windows/crypto/cryptmsg.py
* windows/utils/improved_buffer.py
* windows/utils/pythonutils.py
* windows/winobject/service.py
* windows/debug/symbols.py
* windows/winproxy/ntdll.py
* windows/security.py
* windows/winobject/event_log.py
* windows/winobject/process.py

I didn't test all of them, only several (event_log.py and process.py)

**Comment by hakril** [comment]
Hi,

Thanks for the issue, this is indeed problematic. I may have overlooked that as I still do not use PFW with py3 very often.
Moreover it demonstrated a lack of testing in some of these features.

I have added tests that should trigger each of the reported missing reference as well as the corresponding fixes.

Feel free to reopen the issue if some are still missing.
