### ISSUE TITLE
mistake done while porting PythonForWindows from python2 to python3

### ISSUE THREAD

**Issue by gogo2464** [hakril/PythonForWindows#23]
I have an issue with this library. In order to keep it simple I minimized the code with an example from PythonForWindows.
The following code works on python2:

```import ctypes
import windows
from windows.dbgprint import dbgprint
from windows.generated_def import PROCESS_INFORMATION, STARTUPINFOA


def create_process(path, args=None, dwCreationFlags=0, show_windows=True):
    """A convenient wrapper arround :func:`windows.winproxy.CreateProcessA`"""
    proc_info = PROCESS_INFORMATION()
    lpStartupInfo = None
    if show_windows:
        StartupInfo = STARTUPINFOA()
        StartupInfo.cb = ctypes.sizeof(StartupInfo)
        StartupInfo.dwFlags = 0
        lpStartupInfo = ctypes.byref(StartupInfo)
    lpCommandLine = None
    if args:
        lpCommandLine = (b" ".join([a for a in args]))
    windows.winproxy.CreateProcessA(path, lpCommandLine=lpCommandLine, dwCreationFlags=dwCreationFlags, lpProcessInformation=ctypes.byref(proc_info), lpStartupInfo=lpStartupInfo)
    dbgprint("CreateProcessA new process handle {:#x}".format(proc_info.hProcess), "HANDLE")
    dbgprint("CreateProcessA new thread handle {:#x}".format(proc_info.hThread), "HANDLE")
    dbgprint("Automatic close of thread handle {:#x}".format(proc_info.hThread), "HANDLE")
    windows.winproxy.CloseHandle(proc_info.hThread)  # Give access to a WinThread in addition of the WinProcess ?
    return windows.winobject.process.WinProcess(pid=proc_info.dwProcessId, handle=proc_info.hProcess)

create_process("C:/Users/MYNAME-TRUNCATED/Desktop/coucou-printf.exe")
````

I can see the expected output ("hello world").

Sadly, launched with python3.9, the same code returns:

```Traceback (most recent call last):
  File "C:\Users\MYNAME-TRUNCATED\PycharmProjects\pythonProject\main.py", line 26, in <module>
    create_process("C:/Users/MYNAME-TRUNCATED/Desktop/coucou-printf.exe")
  File "C:\Users\MYNAME-TRUNCATED\PycharmProjects\pythonProject\main.py", line 19, in create_process
    windows.winproxy.CreateProcessA(path, lpCommandLine=lpCommandLine, dwCreationFlags=dwCreationFlags, lpProcessInformation=ctypes.byref(proc_info), lpStartupInfo=lpStartupInfo)
  File "C:\Users\MYNAME-TRUNCATED\PycharmProjects\pythonProject\venv\lib\site-packages\windows\winproxy\apis\kernel32.py", line 50, in CreateProcessA
    return CreateProcessA.ctypes_function(lpApplicationName, lpCommandLine, lpProcessAttributes, lpThreadAttributes, bInheritHandles, dwCreationFlags, lpEnvironment, lpCurrentDirectory, lpStartupInfo, lpProcessInformation)
  File "C:\Users\MYNAME-TRUNCATED\PycharmProjects\pythonProject\venv\lib\site-packages\windows\winproxy\apiproxy.py", line 99, in perform_call
    return self._cprototyped(*args)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

Process finished with exit code 1
```

Then I realize we have to fix this issue in this library in order to fix my issue in my project.

**Comment by hakril** [comment]
Hello,

Indeed, as the `windows.utils.create_process` function was using `CreateProcessA` and not `CreateProcessW`. And so it expected `bytes` in py3 which is not obvious nor natural. I changed that in  8b90c96c and added some associated tests.

Do not hesitate to come back to me (and reopen the issue) if this fix does not work for you.

**Comment by gogo2464** [comment]
@hakril I may have done a mistake but I think the method import from PEFile does not supports python3.

I tried :
```
        if dll in pe.imports:
            for imp in pe.imports[dll]:
                if imp.name == function:
                    return imp.addr

        raise Exception("Error: dll ({0}) or function({1}) not found".format(dll, function))
```

but the exception is alway raised. I read the comments https://github.com/hakril/PythonForWindows/blob/master/windows/pe_parse.py#L434 and particulary the comment https://github.com/hakril/PythonForWindows/blob/master/windows/pe_parse.py#L448 that triggers my attention.


Could you tell me if there is a bug in PythonForWindows please?

**Comment by hakril** [comment]
Hi, could you provide the whole code triggering your bug ?
I would like to see that is the value of `function` in this snippet your provided.

**Comment by gogo2464** [comment]
The full code is here: https://github.com/gogo2464/pwintools/blob/port_to_python3/pwintools.py#L760 The method in question is get_import()

**Comment by hakril** [comment]
Could you provide an exemple where you call the function `get_import()` my goal is to see what is passed as the `function` paramenter.

**Comment by gogo2464** [comment]
I do `p.get_import("kernel32.dll", "WinExec")` here: https://github.com/gogo2464/pwintools/blob/port_to_python3/pwintools.py#L926

**Comment by hakril** [comment]
Ok, thank you for the details.
Two questions:
- What does the line `print(pe.imports)` in you function `get_import()` prints ?(https://github.com/gogo2464/pwintools/blob/port_to_python3/pwintools.py#L762).
- Have you pulled the latest commit of PythonForWindows ? (https://github.com/hakril/PythonForWindows/commit/af7e64638c4a4c17c8427a4481dff9c821ae5943)
I had some bug in the parsing of PE generated by LIEF that was fixed in this commit.

**Comment by gogo2464** [comment]
-`pe.imports` returns `{}`
-AH yes I just removed the pip installation of PythonForWindows and let the requirements build PythonForWindows from source in PyCHarm and then I can see the return address.


Thank you very much. Issue closed.
