### ISSUE TITLE
Idea: External thread trace

### ISSUE THREAD

**Issue by ghost** [hakril/PythonForWindows#31]
Can you implement external thread tracing using OpenThread, GetThreadContext, many threads and a disassembler to stitch together the trace log?

It would be awesome for finding functions in a program with only 1 thread handle. Think function call count etc. All the ways I have seen require you to have a breakpoint at all calls or a module inside the process.

**Comment by hakril** [comment]
Well, as this request is not and bug but a non-trivial feature request and that the user account has been deleted, I am closing this issue.
If anyone feels it needs the request, I will glady take pull-request.
