### ISSUE TITLE
make a new release on pipy

### ISSUE THREAD

**Issue by gogo2464** [hakril/PythonForWindows#32]
The latest version of PythonForWndows fix some bugs. I need it on pipy to avoid to install the git version on setup.py for my software.

Could you make a new release on pipy please?

**Comment by hakril** [comment]
Hi.

Thank you for the issue.
A new version of PythonForWindows (6.5) was released on PyPi : https://pypi.org/project/PythonForWindows/

I am closing this issue,
Thank you,
