### ISSUE TITLE
bug on handle: AttributeError: 'NoneType' object has no attribute 'CloseHandle'

### ISSUE THREAD

**Issue by gogo2464** [hakril/PythonForWindows#35]
After my program I got 

windows\winobject\handle.py", line 117, in __del__
AttributeError: 'NoneType' object has no attribute 'CloseHandle'
Exception ignored in: <function Process.__del__ at 0x000002812A617E50>
Traceback (most recent call last):

I think this is an issue in the library PythonForWindows at the line https://github.com/hakril/PythonForWindows/blob/master/windows/winobject/handle.py#L117 because __del__ is tricky and should be avoided.

I did not locate my error in my code where the issue occures yet. I have to spend timme to find it. This could be a typo for `_handle`.

**Comment by hakril** [comment]
Fixed in f9df80ca
