### ISSUE TITLE
Bug while delete the process WinProcess: TypeError: super() argument 1 must be type, not None

### ISSUE THREAD

**Issue by gogo2464** [hakril/PythonForWindows#37]
At the end of my program that uses an instance of WinProcess, I get this bug:

Exception ignored in: <function Process.__del__ at 0x000001F608807160>
Traceback (most recent call last):
  File "C:\Users\ME\Desktop\pwntools\venv\lib\site-packages\windows\winobject\process.py", line 513, in __del__
TypeError: super() argument 1 must be type, not None

The line in question is super(Process, self).__del__() because the class process is already clened when deleted again.

I see a patch like:
```
if self is not None:
    super(Process, self).__del__()
```

**Comment by hakril** [comment]
Hi,
Thank you for the issue,
Given the error message I guess we should be checking that `Process is not None` instead of `self is not None`.
But i would like to try to identify the cause of this, can you give me a way to reproduce the bug please ?
