### ISSUE TITLE
curious question about querying AD/WMI over the network

### ISSUE THREAD

**Issue by commandline-be** [hakril/PythonForWindows#39]
Hey

Looking to query an AD over the LAN i'm curious if PythonForWindows supports this. The idea is to query installed software, users and their privileges for data colletion and then parse this data into an excel.

br,

JL

**Comment by hakril** [comment]
Hi,

PythonForWindows should be able to connect/query other computers of the domain via WMI (as is is a capability of WMI).
I, myself, have never tested this feature but you should be able to try using something like the following snippet :

```python
import windows
windows.com.init()
# https://docs.microsoft.com/en-us/windows/win32/api/wbemcli/nf-wbemcli-iwbemlocator-connectserver
namespace = windows.winobject.wmi.WmiNamespace.connect(r"\TARGET_SRV\root\cimv2", user=username, password=password)
print(namespace.select("Win32_Process"))
```

I guess you might not need a user/password if you use a privileged account of the domain but I am not sure.
If you test this, I would take any feedback about  how it worked for you or not as I never tried that on a domain.

Thank you,
