### ISSUE TITLE
how to use RtlMoveMemory?

### ISSUE THREAD

**Issue by Justice-Wayne** [hakril/PythonForWindows#43]
sorry , l  search RtlMoveMemory is null ,how to use?

**Comment by hakril** [comment]
Hi,

You may be able to use `ctypes.memmove` to copy memory around. (https://docs.python.org/3/library/ctypes.html#ctypes.memmove)
If you really need `RtlMoveMemory`, I can add  a `windows.winproxy.RtlMoveMemory`.

**Comment by Justice-Wayne** [comment]
Thank you for your reply，

If don't waste your time，Of course I will said yes hhhhh。

**Comment by hakril** [comment]
I have added the function in 09fa7c49.

Thank you for your issue, do not hesitate if you have any feedbacks or questions.
