### ISSUE TITLE
meeting of the minds..

### ISSUE THREAD

**Issue by kdschlosser** [hakril/PythonForWindows#7]
OK so I can see that you have written wrappers for various portions of the Windows API.
I am also in the process of doing the same..well sort of. I am not writing wrappers I am converting the entire Windows 10 SDK to python. 

it can be viewed here. 
https://github.com/kdschlosser/pyWinAPI

I am not done with it yet. and I still have quite a bit to do.  I thought you may be interested. I have also written a C/C++ code parser. it handles h and idl files. it is about 90% accurate in file conversions and it also handles preprocessor macro definitions. The output files do need to be visually inspected and any corrections made. But it sure is a hell of a time saver.

I thought you might want to have a look and maybe you might have some suggestions and comments. I am always looking for feedback.

**Comment by hakril** [comment]
Hi,
Your project seems interesting, I would be glad to exchange with you about it.
I don't think a github issue is the best way to communicate.
You can reach me thought twitter (@hakril), IRC-freenode or email (pfw[at]hakril[dot]net).
