### ISSUE TITLE
 PythonForWindows & python 3

### ISSUE THREAD

**Issue by quentinhardy** [hakril/PythonForWindows#9]
Hello,

Thank you for this project :+1:

For information, do you know when a python 3 version will be released ?

Regards,

**Comment by hakril** [comment]
Hello,

I started working on the subject again at the beginning of january.
I hope to have a beta version passing the tests at the end of january :)

**Comment by hakril** [comment]
Hello,

I continued to work on the subject of python3.
In its current state, the dev branch (02b2ba1) seems to pass all the tests on python3.6.
Feel free to try it out and give me some feedback :)

**Comment by hakril** [comment]
In its current state all the tests on master pass on python2.7/python3.6.
Python3 can now be installed and used from the master branch of PFW !
I am closing this issue, I am well aware that I will still have some python3-related bugs and I hope users will create issues for these.
I won't do a release right now as I want to wait for some feedbacks and take time to update the documentation.
